#!/usr/bin/env ruby

require 'optparse'

def start_server()
	if File.exists?("./src/mvs.pid") == false
		system("cd ./src; nohup rackup -E production -p 8080 -s mongrel -P mvs.pid &")
	end
end

################################################################
## stop_server 
################################################################
def stop_server()
	pid_path = File.join(File.dirname(__FILE__), "src/mvs.pid")

	if File.exists?(pid_path)
    		pid = File.open(pid_path).first.to_i
		if pid > 1
			Process.kill("TERM", pid)
		end
	end
end

def devel_mode()
	puts "Development Mode\n"
	system("cd ./src; rackup -E development -p 8080 -s mongrel")
end

def install_depends()
	system("sudo gem install rack")
	system("sudo gem install mongrel")
	system("sudo gem install sinatra")
	system("sudo gem install browser")
	system("sudo gem install haml")
	system("sudo gem install nokogiri")
end

def build_release()
	build_dir = File.join(File.dirname(__FILE__), "build/")
	docs_dir = File.join(File.dirname(__FILE__), "docs/")

	if File.exists?(build_dir)
		system("rm -r build/")
	end

	Dir.mkdir(build_dir)

	if File.exists?(docs_dir)
		system("rm -r docs/")
	end

	Dir.mkdir(docs_dir)

	system("tar -czf build/mvs.tar.gz mvsctl docs/ src/config.ru src/MovieStreamer.rb")

	system("haml src/views/browsers.haml docs/Supported_Browsers.html")
	system("haml src/views/readme.haml docs/ReadMe.html")
end

################################################################
# change_directory
################################################################
def change_directory( path )
	public_path = File.join(File.dirname(__FILE__), "src/public")

	if File.exists?(public_path)
		File.unlink(public_path)
	end
	
	File.symlink(path, public_path)
end

options = {}

optparse = OptionParser.new do |opts|

    opts.banner = "Usage: mvsctl [options]"

	opts.on('-s', '--start', 'Start Server') do
		start_server	
	end

	opts.on('-x', '--stop', 'Stop Server') do
		stop_server	
	end

	opts.on('-d', '--devel', 'Development Mode') do 
		devel_mode	
	end

	opts.on('-i', '--install', 'Install Dependencies') do
		install_depends	
	end

	opts.on('-b', '--build', 'Build a release') do
        build_release	
	end

	opts.on('-c', '--change PATH', 'Change the movie directory') do |p|
		change_directory p	
	end 

	opts.on('-h', '--help', 'Display this screen') do
        puts opts
        exit
    end
end

begin
	optparse.parse!
rescue Exception => e
	puts "Exception Occured: #{e}"
	exit 1
end
