#!/usr/bin/env ruby

require 'optparse'

def start_server()
	puts "Start Server\n"
end

def stop_server()
	puts "Stop Server\n"
end

def devel_mode()
	puts "Development Mode\n"
end

def install_depends()
	puts "Install Dependencies"
end

def build_release()
	puts "Build a Release"
end

def change_directory( path )
	puts path
end

options = {}

optparse = OptionParser.new do |opts|

        opts.banner = "Usage: mvsctl [options]"

	opts.on('-s', '--start', 'Start Server') do
		start_server	
	end

	opts.on('-x', '--stop', 'Stop Server') do
		stop_server	
	end

	opts.on('-d', '--devel', 'Development Mode') do 
		devel_mode	
	end

	opts.on('-i', '--install', 'Install Dependencies') do
		install_depends	
	end

	opts.on('-b', '--build', 'Build a release') do
       		build_release	
	end

	opts.on('-c', '--change PATH', 'Change the movie directory') do |p|
		change_directory p	
	end 

	opts.on('-h', '--help', 'Display this screen') do
                puts opts
                exit
        end
end

optparse.parse!
